separator = "|"
separator_color = "yellow"
key_color = "blue"
prefer_small_ascii = true
padding = 0

[palette]
type = "Light"
visible = true
glyph = "󰝤󰝤󰝤󰝤󰝤󰝤󰝤"

[box]
title = " CATFETCH "
border = "thick"
visible = true

[custom_ascii]
color = "magenta"
path = "~/.config/macchina/themes/ascii.txt"

[bar]
glyph = "󰝤󰝤"
hide_delimiters = true
visible = true

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
distro = "OS"
packages = "Packages"
terminal = "Terminal"
shell = "Shell"
cpu = "CPU"
cpu_load = "Load"
memory = "Memory"
battery = "Battery"

